[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [ThinkPad](bold yellow) '
trim_at = "."
disabled = false

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"

[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[battery]
disabled = true

[git_commit]
commit_hash_length = 8
style = "bold white"

[aws]
disabled = true
symbol = "  "

[gcloud]
disabled = true

[nodejs]
disabled = false
style = 'bold green'
symbol = ' '

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false
