import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[env]
TERM = "screen-256color"

[window]
padding.x = 0
padding.y = 0

opacity = 0.9
blur = true

startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11.3

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[keyboard]
bindings = [{ key = "N", mods = "Control | Shift", action = "CreateNewWindow" }]
